name: Deploy our project using SSH to AWS Server
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Project Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
