name: Check and deploy our project using SSH to Azure Server
on: [push]
jobs:
  style:
    name: WeBot Code Style
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install flake8
          python -m pip install flake8-github-actions
      - name: "Run Flake8"
        # flake8 do not understand imports that persist in another file
        run: "flake8 --format github --extend-ignore=F401,F403,F405 --max-line-length 200 || true"

  tests:
    name: WeBot Tests
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Setup Python
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          python -m pip install -r api/requirements.txt
          python -m pip install -r bot/requirements.txt
      - name: "Run Pytest"
        run: "pass"
      

  update:
    name: WeBot Update
    runs-on: ubuntu-latest
    steps:
    - name: Update Git repositry dir
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/webot
          git pull

  deploy:
    name: WeBot Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build new Docker Images and run via Docker-Compose
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}  
        port: ${{ secrets.PORT }}
        script: |
          cd ~/webot
          docker-compose build
          docker-compose up -d
